language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      node_js: stable
      sudo: required
      addons:
        apt:
          packages:
          - google-chrome-stable
    - os: osx
      node_js: stable
      osx_image: xcode8.3

before_install:
- npm install google-closure-library
- npm install webdriverio
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( scripts/setup_linux_env.sh  ) fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( scripts/setup_osx_env.sh ) fi
  - sleep 2

script:
  - set -x
  - npm test
